# Usa Node come base
FROM node:20-alpine

# Imposta la working directory
WORKDIR /app

# Copia i file di dipendenze
COPY package.json package-lock.json ./

# Installa le dipendenze
RUN npm install

# Copia tutto il progetto
COPY . .

# Usa .env.example come .env per la build del container
RUN cp .env.example .env

# Compila il progetto
RUN npm run build