# Fase di build
FROM node:20 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Fase di produzione
FROM nginx:stable-alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
# Qui --from=build punta all'alias AS build
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
