version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docs/database/db_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./docs/database/db_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    ports:
      - "5434:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      COLLABORA_URL: https://editorgiornaledeilavori.gabrielebuttice.com
      WOPI_BASE_URL: https://giornaledeilavori.gabrielebuttice.com
    ports:
      - "3001:3001"
    depends_on:
      - db
    command: sh -c "npm run migrate && node server.js"

  collabora:
    image: collabora/code
    container_name: collabora
    restart: always
    environment:
      - aliasgroup1=https://giornaledeilavori.gabrielebuttice.com:443
      - DONT_GEN_SSL_CERT=YES
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:net.frame_ancestors=https://giornaledeilavori.gabrielebuttice.com http://localhost:5173
    ports:
      - "9980:9980"
    cap_add:
      - MKNOD
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    restart: always
    environment:
      VITE_BACKEND_URL: ${FRONTEND_BACKEND_URL}
    depends_on:
      - backend
    volumes:
      - /var/www/giornaledeilavori.gabrielebuttice.com/dist:/app/dist_folder_vps
    command: sh -c "cp -r /app/dist/* /app/dist_folder_vps/ && tail -f /dev/null"

volumes:
  postgres_data: